export { assertNever } from './exhaustive.js';
export {
  ALL_EVENTS,
  ALL_STATES,
  INITIAL_CONTEXT,
  TERMINAL_STATE,
  allowedEvents,
  isTerminal,
  transition,
  type ConversationContext,
  type ConversationEventType,
  type ConversationState,
  type TransitionAuditEvent,
  type TransitionInput,
  type TransitionRejection,
  type TransitionResult,
} from './conversation-state.js';
export {
  createEnvelope,
  decideIngest,
  deriveIdempotencyKey,
  deriveSideEffectKey,
  type DeliveryRecord,
  type EnvelopeInput,
  type EnvelopeRejectionReason,
  type EnvelopeResult,
  type InboundEventEnvelope,
  type IngestContext,
  type IngestDecision,
  type ProviderId,
  type RawEventRef,
  type SideEffectKind,
} from './inbound-event.js';
export {
  DEFAULT_POLICY,
  SENSITIVE_CATEGORIES,
  canAskClarification,
  decideHandoff,
  decideResolution,
  deriveFollowUpKey,
  describeDeferralCause,
  describeSensitiveCategory,
  isUsableForCaller,
  planDeferral,
  type CallerIdentity,
  type DeferralCause,
  type DeferralInput,
  type DeferralPlan,
  type FounderReply,
  type GateResult,
  type HandoffDecision,
  type KnowledgeCandidate,
  type KnowledgeScope,
  type KnowledgeStatus,
  type PolicyConfig,
  type ResolutionDecision,
  type ResolutionRequest,
  type SensitiveCategory,
} from './policy.js';
export {
  MAX_CONTEXT_WORDS,
  assessPriority,
  buildEscalationPacket,
  clampContext,
  type CallerSummary,
  type EscalationPacket,
  type FounderAction,
  type PacketInput,
  type PacketRejectionReason,
  type PacketResult,
  type Priority,
  type PriorityAssessment,
  type PrioritySignals,
  type RelationshipStatus,
  type Urgency,
} from './escalation-packet.js';
export {
  deriveConversationFollowUpKey,
  describeDependency,
  planRecovery,
  type DependencyKind,
  type FailureContext,
  type OperatorAlert,
  type RecoveryPlan,
} from './recovery.js';
